name: Staging deployment
# rebuild any PRs and main branch changes
on:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.1
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm run all
      - run: cp action.yml dist/

      - name: Configure git information
        run: |
          git config --global user.name 'Plasmo G.A.T Deployer'
          git config --global user.email 'support@plasmo.com'

      - run: pnpm dlx gh-pages -d dist -b staging

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: staging
      - uses: ./
        with:
          milliseconds: "1000"
